### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by StevenVanDyk** [zarmstrong/hlo-importer#8] opened 2021-04-28 16:59 UTC
**Describe the bug**
Importing Character causes sheet to be unopenable

**To Reproduce**

1. open character
2. Open the import tool
3. Enter token from HLO
4. Click proceed to import.
5. Close the Character 
5. try to open character

**Expected behavior**
Character with information to be imported

**Screenshots**

**File ID this error occurred with**
Please include the File ID produced by your conversion. This can be found by looking at the name of the file you downloaded. If you were unable to download a file, the File ID can be found on the error page.
 
**Additional context**
$pDaWYEQ~@P2#

**Comment by zarmstrong** [comment] 2021-04-28 17:58
Duplicate of #7

**Closed as completed by zarmstrong** 2021-04-28 17:58 UTC
